# Generated by Django 4.2 on 2023-05-09 14:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MoneyChain",
            fields=[
                ("value", models.FloatField(null=True)),
                ("positive", models.BooleanField(default=True)),
                (
                    "ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "next",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_chain",
                        to="debts.moneychain",
                    ),
                ),
                (
                    "previous",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_chain",
                        to="debts.moneychain",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Debt",
            fields=[
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.FloatField(blank=True)),
                (
                    "ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "moneyChain_first_index",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_index",
                        to="debts.moneychain",
                    ),
                ),
                (
                    "moneyChain_last_index",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_index",
                        to="debts.moneychain",
                    ),
                ),
            ],
        ),
    ]
