# Generated by Django 4.1.4 on 2022-12-22 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("name", models.CharField(max_length=120)),
                (
                    "person_ordered_id",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("is_customer", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("in_stock", models.BooleanField(default=False)),
                ("number_in_stock", models.IntegerField(default=0)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
