# Generated by Django 4.1.4 on 2022-12-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="emergency_level",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=6,
            ),
        ),
    ]
