# Generated by Django 4.2 on 2023-04-08 06:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductForOrder",
            fields=[
                ("name", models.CharField(max_length=120)),
                (
                    "person_ordered_id",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("is_customer", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("in_stock", models.BooleanField(default=False)),
                ("number_in_stock", models.IntegerField(default=0)),
                (
                    "emergency_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=6,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
