# Generated by Django 4.2 on 2023-05-28 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("information", models.CharField(max_length=1000)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("TRANSFER", "TRANSFER"),
                            ("CARD", "CARD"),
                            ("CASH", "CASH"),
                        ],
                        max_length=100,
                    ),
                ),
                ("time", models.TimeField(auto_now_add=True)),
                ("amount", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("shift_is_closed", models.BooleanField(default=False)),
                ("cash_left", models.FloatField(default=0)),
                ("terminal_income", models.FloatField(default=0)),
                (
                    "operations",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workday_finance_management.operation",
                    ),
                ),
            ],
        ),
    ]
