# Generated by Django 4.2 on 2023-05-28 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workday_finance_management", "0002_remove_journal_operations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="journal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_operations",
                to="workday_finance_management.journal",
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="operations",
            field=models.ManyToManyField(
                related_name="operations", to="workday_finance_management.operation"
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="operation_type",
            field=models.CharField(
                choices=[("CARD", "CARD"), ("CASH", "CASH"), ("TRANSFER", "TRANSFER")],
                max_length=100,
            ),
        ),
    ]
