# Generated by Django 4.2 on 2023-05-29 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "workday_finance_management",
            "0004_alter_journal_date_alter_operation_operation_type",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="ID",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="operation_type",
            field=models.CharField(
                choices=[("CARD", "CARD"), ("CASH", "CASH"), ("TRANSFER", "TRANSFER")],
                max_length=100,
            ),
        ),
    ]
