# Generated by Django 4.1.4 on 2022-12-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telephone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
